(deftheme monokai-pro
  "Created 2019-05-28.")

(custom-theme-set-variables
 'monokai-pro
 '(ansi-color-names-vector ["#2d2a2e" "#ff6188" "#a9dc76" "#ffd866" "#78dce8" "#ab9df2" "#ff6188" "#fcfcfa"]))

(custom-theme-set-faces
 'monokai-pro
 '(cursor ((t (:background "#fcfcfa"))))
 '(fringe ((t (:background "#403e41"))))
 '(header-line ((t (:inherit mode-line :background nil))))
 '(highlight ((t (:background "#353236" :foreground "#727072"))))
 '(link ((t (:underline t :foreground "#78dce8"))))
 '(link-visited ((t (:underline t :foreground "#ab9df2"))))
 '(minibuffer-prompt ((t (:foreground "#fcfcfa"))))
 '(region ((t (:background "#403e41"))))
 '(secondary-selection ((t (:background "#403e41"))))
 '(trailing-whitespace ((t (:background "#ff6188" :foreground "#fcfcfa"))))
 '(widget-button ((t (:underline t))))
 '(widget-field ((t (:box (:color "#403e41" :line-width 1) :background "#c1c0c0"))))
 '(error ((t (:weight bold :foreground "#ff6188"))))
 '(warning ((t (:weight bold :foreground "#fc9867"))))
 '(success ((t (:weight bold :foreground "#a9dc76"))))
 '(font-lock-builtin-face ((t (:foreground "#ab9df2"))))
 '(font-lock-comment-delimiter-face ((t (:foreground "#727072"))))
 '(font-lock-comment-face ((t (:slant italic :foreground "#727072"))))
 '(font-lock-constant-face ((t (:foreground "#ab9df2"))))
 '(font-lock-doc-face ((t (:foreground "#727072"))))
 '(font-lock-function-name-face ((t (:foreground "#a9dc76"))))
 '(font-lock-keyword-face ((t (:foreground "#ff6188"))))
 '(font-lock-string-face ((t (:foreground "#ffd866"))))
 '(font-lock-type-face ((t (:foreground "#78dce8"))))
 '(font-lock-variable-name-face ((t (:foreground "#fcfcfa"))))
 '(font-lock-warning-face ((t (:foreground "#fc9867"))))
 '(match ((t (:inverse-video t :background "#2d2a2e" :foreground "#ffd866"))))
 '(isearch ((t (:weight bold :background "#ffd866" :foreground "#2d2a2e"))))
 '(lazy-highlight ((t (:inverse-video t :foreground "#c1c0c0"))))
 '(isearch-fail ((t (:background "#fcfcfa" :foreground "#ff6188"))))
 '(mode-line ((t (:background "#353236" :foreground "#939293"))))
 '(mode-line-buffer-id ((t (:background nil :foreground "#ffd866"))))
 '(mode-line-emphasis ((t (:slant italic :foreground "#c1c0c0"))))
 '(mode-line-highlight ((t (:weight bold :box nil :foreground "#fcfcfa"))))
 '(mode-line-inactive ((t (:background "#403e41" :foreground "#939293"))))
 '(diff-added ((t (:foreground "#a9dc76"))))
 '(diff-changed ((t (:foreground "#ab9df2"))))
 '(diff-removed ((t (:foreground "#ff6188"))))
 '(diff-header ((t (:background "#2d2a2e"))))
 '(diff-file-header ((t (:background "#353236"))))
 '(diff-hunk-header ((t (:background "#2d2a2e" :foreground "#ff6188"))))
 '(show-paren-match ((t (:inverse-video t))))
 '(show-paren-mismatch ((t (:inverse-video t :background "#ff6188"))))
 '(default ((t (:background "#2d2a2e" :foreground "#fcfcfa")))))

(provide-theme 'monokai-pro)
